name: CI
on:
  push:
    branches:
      - master #here we choose to deploy only when a push is detected on the main branch
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1 # Use your bucket region here

    # Here you could add some building steps if you were dealing with some angular/react/Vue...
    - name: Build static site
      run: npm install && npm run generate

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./dist/ s3://test-ci-cd-1 --delete
      # --delete flag will remove any file in the s3 that are not on the "thefoldertodeploy" folder
